### ISSUE TITLE
Add Maven Release Plugin

### ISSUE THREAD

**Issue by luisE-dev** [BeiliLu1986/Petclinic#3]

**Comment by BeiliLu1986** [comment]
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project pet-clinic-data: MavenReportException: Error while gen
erating Javadoc:

**Comment by luisE-dev** [comment]
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project pet-clinic-data: MavenReportException: Error while gen
erating Javadoc:
